export enum NotificationType {
  // Vote related
  THREAD_UPVOTE = 'THREAD_UPVOTE',
  THREAD_DOWNVOTE = 'THREAD_DOWNVOTE',
  COMMENT_UPVOTE = 'COMMENT_UPVOTE',
  COMMENT_DOWNVOTE = 'COMMENT_DOWNVOTE',
  NEW_COMMENT = 'NEW_COMMENT',
  VOTE_MILESTONE = 'VOTE_MILESTONE',
  VOTE_REMOVED = 'VOTE_REMOVED',
  
  // Thread related
  NEW_THREAD_FOLLOWED = 'NEW_THREAD_FOLLOWED',
  THREAD_UPDATED = 'THREAD_UPDATED',
  THREAD_DELETED = 'THREAD_DELETED',
  
  // Comment related
  NEW_COMMENT_ON_THREAD = 'NEW_COMMENT_ON_THREAD',
  NEW_COMMENT_ON_FOLLOWED_THREAD = 'NEW_COMMENT_ON_FOLLOWED_THREAD',
  COMMENT_REPLY = 'COMMENT_REPLY',
  COMMENT_DELETED = 'COMMENT_DELETED',
  
  // User related
  USER_FOLLOWED = 'USER_FOLLOWED',
  USER_UNFOLLOWED = 'USER_UNFOLLOWED',
  USER_MENTIONED = 'USER_MENTIONED',
  
  // System related
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION'
} 